### ISSUE TITLE
[PE-D][Tester E] `addfield` and `editfield` are unknown commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#116] opened 2022-10-29 02:46 UTC
## Description

When testing out the `addfield` and `editfield` commands, the "Unknown command" error were raised. This is not a expected behavior for users as `addfield` and `editfield` is documented in the User Guide

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/2774d1d8-9fac-4122-9113-2db21aa4d968.png)

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/d39ba542-fd1b-4899-9773-f3d37862338d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: shenyih0ng/ped#7

**Comment by Eclipse-Dominator** [comment] 2022-11-01 03:22
This is a documentation bug. 

This correct syntax should be 
- `field add<t|g|u>/<index><type> <value>` 
- `<selected item> field add <type> <value>`

- `field edit<t|g|u>/<index><type> <value>` 
- `<selected item> field edit <type> <value>`

**Comment by Eclipse-Dominator** [comment] 2022-11-01 18:15
Duplicate of #107

**Closed by Eclipse-Dominator** 2022-11-01 18:15 UTC
Labels: documentation bug
