### ISSUE TITLE
[PE-D][Tester B] Edit field to task is not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#133] opened 2022-10-29 03:47 UTC
![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/d1ec9d81-e31c-4afc-b31a-ad9e1929e7bc.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ThomasHoooo/ped#18

**Comment by Eclipse-Dominator** [comment] 2022-11-01 03:10
This is a documentation bug. 

This correct syntax should be 
- `field edit <t|g|u>/<index><type> <value>` 
- `<selected item> field <type> <value>`

**Comment by Eclipse-Dominator** [comment] 2022-11-01 18:16
Duplicate of #107

**Closed by Eclipse-Dominator** 2022-11-01 18:16 UTC
Labels: documentation bug
