### ISSUE TITLE
[PE-D][Tester B] Edit field prompts unknown command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#113] opened 2022-10-29 02:36 UTC
I followed exactly according to the userguide.

![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/eccfd25b-1088-4a45-9017-f08c50c89e74.png)

Userguide:

![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/d608d809-37c6-459d-b3d2-ff7b8cd700b4.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: ThomasHoooo/ped#11

**Comment by Eclipse-Dominator** [comment] 2022-11-01 03:23
This is a documentation bug

The correct syntax should be:
- `field edit <t|g|u>/<index><type> <value>` 
- `<selected item> field edit <type> <value>`

**Comment by Eclipse-Dominator** [comment] 2022-11-01 18:13
Duplicate of #107

**Closed by Eclipse-Dominator** 2022-11-01 18:13 UTC
Labels: documentation bug
